project:
  type: website

website:
  title: "LI-HSUAN CHUNG's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lihsuanchung
format:
  html:
    theme: superhero
    css: styles.css



